// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpmnhwrfboaivkulhpde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwbW5od3JmYm9haXZrdWxocGRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNzc3NjgsImV4cCI6MjA1Njk1Mzc2OH0.QJi612PV4zVcACnxiCwtPcko-9WPMuNbDTmKhwVeQcY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);